# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: yearn-v3-vault
description: Yearn V3 Vault Indexer
field_selection:
  transaction_fields:
    - hash
    - from
contracts:
  - name: YearnV3Vault
    handler: src/EventHandlers.ts
    events:
      - event: "Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)"
      - event: "Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)"
      - event: "Transfer(address indexed sender, address indexed receiver, uint256 value)"
      - event: "StrategyReported(address indexed strategy, uint256 gain, uint256 loss, uint256 current_debt, uint256 protocol_fees, uint256 total_fees, uint256 total_refunds)"
      - event: "DebtUpdated(address indexed strategy, uint256 current_debt, uint256 new_debt)"
      - event: "DebtPurchased(address indexed strategy, uint256 amount)"
      - event: "StrategyChanged(address indexed strategy, uint256 indexed change_type)"
      - event: "UpdatedMaxDebtForStrategy(address indexed sender, address indexed strategy, uint256 new_debt)"
      - event: "RoleSet(address indexed account, uint256 indexed role)"
      - event: "UpdateFutureRoleManager(address indexed future_role_manager)"
      - event: "UpdateRoleManager(address indexed role_manager)"
      - event: "UpdateAccountant(address indexed accountant)"
      - event: "UpdateDefaultQueue(address[] new_default_queue)"
      - event: "UpdateUseDefaultQueue(bool use_default_queue)"
      - event: "UpdateAutoAllocate(bool auto_allocate)"
      - event: "UpdateDepositLimit(uint256 deposit_limit)"
      - event: "UpdateDepositLimitModule(address indexed deposit_limit_module)"
      - event: "UpdateWithdrawLimitModule(address indexed withdraw_limit_module)"
      - event: "UpdateMinimumTotalIdle(uint256 minimum_total_idle)"
      - event: "UpdateProfitMaxUnlockTime(uint256 profit_max_unlock_time)"
      - event: "Shutdown()"
  - name: TimelockController
    handler: src/EventHandlers.ts
    events:
      - event: "CallScheduled(bytes32 indexed id, uint256 indexed index, address target, uint256 value, bytes data, bytes32 predecessor, uint256 delay)"
  - name: AaveTimelock
    handler: src/EventHandlers.ts
    events:
      - event: "ProposalQueued(uint256 indexed proposalId, uint128 votesFor, uint128 votesAgainst)"
  - name: CompoundTimelock
    handler: src/EventHandlers.ts
    events:
      - event: "QueueTransaction(bytes32 indexed txHash, address indexed target, uint value, string signature, bytes data, uint eta)"
  - name: PufferTimelock
    handler: src/EventHandlers.ts
    events:
      - event: "TransactionQueued(bytes32 indexed txHash, address indexed target, bytes callData, uint256 indexed operationId, uint256 lockedUntil)"
  - name: LidoTimelock
    handler: src/EventHandlers.ts
    events:
      - event: "StartVote(uint256 indexed voteId, address indexed creator, string metadata)"
  - name: MapleTimelock
    handler: src/EventHandlers.ts
    events:
      - event: "ProposalScheduled(uint256 indexed proposalId, (bytes32, bool, uint32, uint32, uint32) proposal)"
  - name: YearnReferralWrapper
    handler: src/EventHandlers.ts
    events:
      - event: "ReferralDeposit(address receiver, address indexed referrer, address indexed vault, uint256 assets, uint256 shares)"
networks:
  - id: 1
    start_block: 0
    contracts:
      - name: YearnV3Vault
        address:
          - "0xBe53A109B494E5c9f97b9Cd39Fe969BE68BF6204" # USDC-1
          - "0x028eC7330ff87667b6dfb0D94b954c820195336c" # DAI-1
          - "0x310B7Ea7475A0B449Cfd73bE81522F1B88eFAFaa" # USDT-1
          - "0x182863131F9a4630fF9E27830d945B1413e347E8" # USDS-1
          - "0xBF319dDC2Edc1Eb6FDf9910E39b37Be221C8805F" # CRVUSD-2
          - "0xc56413869c6CDf96496f2b1eF801fEDBdFA7dDB0" # WETH-1
          - "0xAc37729B76db6438CE62042AE1270ee574CA7571" # WETH-2
          - "0x751F0cC6115410A3eE9eC92d08f46Ff6Da98b708" # WBTC-1
          - "0xAe7d8Db82480E6d8e3873ecbF22cf17b3D8A7308" # USDC-2
          - "0x92545bCE636E6eE91D88D2D017182cD0bd2fC22e" # DAI-2
          - "0x9F4330700a36B29952869fac9b33f45EEdd8A3d8" # yBOLD
          - "0x89E93172AEF8261Db8437b90c3dCb61545a05317" # sUSDaf
          - "0x1F6f16945e395593d8050d6Cc33e4328a515B648" # yYB
          - "0xaF71a4f5d93fb88B24C67760BCF9688a6C3A54D4" # SKY
      - name: TimelockController
        address:
          - "0xd8236031d8279d82e615af2bfab5fc0127a329ab" # CAP TimelockController
          - "0x5d8a7dc9405f08f14541ba918c1bf7eb2dace556" # ETH+ Timelock
          - "0x055e84e7fe8955e2781010b866f10ef6e1e77e59" # LombardTimeLock
          - "0xe1f03b7b0ebf84e9b9f62a1db40f1efb8faa7d22" # Silo TimelockController
          - "0x81f6e9914136da1a1d3b1efd14f7e0761c3d4cc7" # Renzo(ezETH) TimelockController
          - "0x9f26d4c958fd811a1f59b01b86be7dffc9d20761" # EtherFiTimelock
          - "0x49bd9989e31ad35b0a62c20be86335196a3135b1" # KelpDAO(rsETH) Timelock
          - "0x3D18480CC32B6AB3B833dCabD80E76CfD41c48a9" # Infinifi Longtimelock
          - "0x4B174afbeD7b98BA01F50E36109EEE5e6d327c32" # Infinifi Shorttimelock
      - name: AaveTimelock
        address:
          - "0x9aee0b04504cef83a65ac3f0e838d0593bcb2bc7" # Aave Timelock
      - name: CompoundTimelock
        address:
          - "0x6d903f6003cca6255d85cca4d3b5e5146dc33925" # Compound Timelock
          - "0x2386dc45added673317ef068992f19421b481f4c" # Fluid Timelock
      - name: PufferTimelock
        address:
          - "0x3c28b7c7ba1a1f55c9ce66b263b33b204f2126ea" # Puffer Timelock
      - name: LidoTimelock
        address:
          - "0x2e59a20f205bb85a89c53f1936454680651e618e" # Lido Timelock
      - name: MapleTimelock
        address:
          - "0x2efff88747eb5a3ff00d4d8d0f0800e306c0426b" # Maple GovernorTimelock
      - name: YearnReferralWrapper
        address:
          - "0x3744Df2673097d738aCaa3E463E6D638867757f2"
  - id: 8453
    start_block: 0
    contracts:
      - name: YearnV3Vault
        address:
          - "0xb13CF163d916917d9cD6E836905cA5f12a1dEF4B" # USDC True Yield
          - "0xc3BD0A2193c8F027B82ddE3611D18589ef3f62a9" # USDC Horizon
          - "0x4d81C7d534D703E0a0AECaDF668C0E0253E1f1C3" # WETH Horizon
          - "0x25f32eC89ce7732A4E9f8F3340a09259F823b7d3" # cbBTC Horizon
          - "0x989381F7eFb45F97E46BE9f390a69c5d94bf9e17" # cbETH Horizon
      - name: TimelockController
        address: "0xf817cb3092179083c48c014688d98b72fb61464f" # superOETH Timelock
      - name: YearnReferralWrapper
        address:
          - "0x3744Df2673097d738aCaa3E463E6D638867757f2"
  - id: 42161
    start_block: 0
    contracts:
      - name: YearnV3Vault
        address:
          - "0x252b965400862d94BDa35FeCF7Ee0f204a53Cc36" # USND
          - "0x9FA306b1F4a6a83FEC98d8eBbaBEDfF78C407f6B" # USDC.e-2
          - "0x6FAF8b7fFeE3306EfcFc2BA9Fec912b4d49834C1" # USDC-A
          - "0xc0ba9bfED28aB46Da48d2B69316A3838698EF3f5" # USDT-A
          - "0x7DEB119b92b76f78C212bc54FBBb34CEA75f4d4A" # ARB-1
      - name: YearnReferralWrapper
        address:
          - "0x3744Df2673097d738aCaa3E463E6D638867757f2"
  - id: 137
    start_block: 0
    contracts:
      - name: YearnV3Vault
        address:
          - "0x34b9421Fe3d52191B64bC32ec1aB764dcBcDbF5e" # USDC
          - "0xA013Fbd4b711f9ded6fB09C1c0d358E2FbC2EAA0" # USDC.e
          - "0xBb287E6017d3DEb0e2E65061e8684eab21060123" # USDT
          - "0x90b2f54C6aDDAD41b8f6c4fCCd555197BC0F773B" # DAI
          - "0x305F25377d0a39091e99B975558b1bdfC3975654" # WETH
          - "0x28F53bA70E5c8ce8D03b1FaD41E9dF11Bb646c36" # WMATIC
  # - id: 747474
  #   start_block: 0
  #   contracts:
  #     - name: YearnV3Vault
  #       address:
  #         - "0x80c34BD3A3569E126e7055831036aa7b212cB159" # USDC
  #         - "0xE007CA01894c863d7898045ed5A3B4Abf0b18f37" # WETH
  #         - "0x9A6bd7B6Fd5C4F87eb66356441502fc7dCdd185B" # USDT
  #         - "0xAa0362eCC584B985056E47812931270b99C91f9d" # WBTC
  #     - name: YearnReferralWrapper
  #       address:
  #         - "0x3744Df2673097d738aCaa3E463E6D638867757f2"
unordered_multichain_mode: true
preload_handlers: true
address_format: lowercase
